// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package invitecodes

import (
	"context"
)

type Querier interface {
	AtomicUseInviteCode(ctx context.Context, arg AtomicUseInviteCodeParams) error
	CountInviteCodesByRedeemedBy(ctx context.Context, redeemedBy *string) (int64, error)
	CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (InviteCode, error)
	GetAllInviteCodes(ctx context.Context) ([]InviteCode, error)
	GetInviteCodeByCodeHash(ctx context.Context, codeHash string) (InviteCode, error)
	GetInviteCodeByID(ctx context.Context, id int64) (InviteCode, error)
	ResetInviteCode(ctx context.Context, codeHash string) error
	SoftDeleteInviteCode(ctx context.Context, id int64) error
	UpdateInviteCodeActive(ctx context.Context, arg UpdateInviteCodeActiveParams) error
	UpdateInviteCodeUsage(ctx context.Context, arg UpdateInviteCodeUsageParams) error
}

var _ Querier = (*Queries)(nil)
