// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgdb

import (
	"time"
)

type InviteCode struct {
	ID         int64      `json:"id"`
	Code       string     `json:"code"`
	CodeHash   string     `json:"codeHash"`
	BoundEmail *string    `json:"boundEmail"`
	CreatedBy  int64      `json:"createdBy"`
	IsUsed     bool       `json:"isUsed"`
	RedeemedBy *string    `json:"redeemedBy"`
	RedeemedAt *time.Time `json:"redeemedAt"`
	ExpiresAt  *time.Time `json:"expiresAt"`
	IsActive   bool       `json:"isActive"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
}

type RequestLog struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"userId"`
	Endpoint  string    `json:"endpoint"`
	Model     *string   `json:"model"`
	Provider  string    `json:"provider"`
	CreatedAt time.Time `json:"createdAt"`
}

type UserRequestCountsDaily struct {
	UserID       string `json:"userId"`
	DayBucket    int64  `json:"dayBucket"`
	RequestCount int64  `json:"requestCount"`
}
