// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: request_logs.sql

package pgdb

import (
	"context"
	"time"
)

const createRequestLog = `-- name: CreateRequestLog :exec
INSERT INTO request_logs (user_id, endpoint, model, provider) 
VALUES ($1, $2, $3, $4)
`

type CreateRequestLogParams struct {
	UserID   string  `json:"userId"`
	Endpoint string  `json:"endpoint"`
	Model    *string `json:"model"`
	Provider string  `json:"provider"`
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) error {
	_, err := q.db.ExecContext(ctx, createRequestLog,
		arg.UserID,
		arg.Endpoint,
		arg.Model,
		arg.Provider,
	)
	return err
}

const getUserRequestCountInLastDay = `-- name: GetUserRequestCountInLastDay :one
SELECT COALESCE(SUM(request_count), 0)::BIGINT as total_requests
FROM user_request_counts_daily 
WHERE user_id = $1 
  AND day_bucket >= DATE_TRUNC('day', NOW()) - INTERVAL '1 day'
`

func (q *Queries) GetUserRequestCountInLastDay(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserRequestCountInLastDay, userID)
	var total_requests int64
	err := row.Scan(&total_requests)
	return total_requests, err
}

const getUserRequestCountInTimeWindow = `-- name: GetUserRequestCountInTimeWindow :one
SELECT COUNT(*) 
FROM request_logs 
WHERE user_id = $1 
  AND created_at >= $2
`

type GetUserRequestCountInTimeWindowParams struct {
	UserID    string    `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) GetUserRequestCountInTimeWindow(ctx context.Context, arg GetUserRequestCountInTimeWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserRequestCountInTimeWindow, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refreshUserRequestCountsView = `-- name: RefreshUserRequestCountsView :exec
REFRESH MATERIALIZED VIEW CONCURRENTLY user_request_counts_daily
`

func (q *Queries) RefreshUserRequestCountsView(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, refreshUserRequestCountsView)
	return err
}
