resources:
- '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret
  name: mtls
  tls_certificate:
    certificate_chain:
      filename: /var/run/secrets/mtls/tls.crt
    private_key:
      filename: /var/run/secrets/mtls/tls.key
