[processes.dnsmasq]
command = "dnsmasq -dhR -H /etc/hosts.enclave -a 127.0.0.1 -A /./127.0.0.1"

[processes.envoy]
command = "envoy -l warning --component-log-level misc:error --concurrency 4 -c /etc/envoy/envoy.yaml"

[processes.node_exporter]
command = "node_exporter --web.listen-address=127.0.0.1:9100 --log.level=warn"

[processes.server]
command = "server.sh"
