// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Telegram Chat represents a Telegram chat
type Chat struct {
	ID        int     `json:"id"`
	Type      string  `json:"type"`
	Title     *string `json:"title,omitempty"`
	Username  *string `json:"username,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

// Telegram Message represents a message from Telegram
type Message struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	ChatID    int    `json:"chatId"`
	ChatUUID  string `json:"chatUUID"`
	From      *User  `json:"from"`
	Date      int    `json:"date"`
	MessageID int    `json:"messageId"`
	Role      string `json:"role"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

// Telegram User represents a user who sent a message
type User struct {
	ID        int     `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  *string `json:"lastName,omitempty"`
	Username  *string `json:"username,omitempty"`
}
