// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apple_transactions.sql

package pgdb

import (
	"context"
)

const getAppleTransaction = `-- name: GetAppleTransaction :one
SELECT original_transaction_id, user_id, product_id, tier, redeemed_at
FROM apple_transactions
WHERE original_transaction_id = $1
`

func (q *Queries) GetAppleTransaction(ctx context.Context, originalTransactionID string) (AppleTransaction, error) {
	row := q.db.QueryRowContext(ctx, getAppleTransaction, originalTransactionID)
	var i AppleTransaction
	err := row.Scan(
		&i.OriginalTransactionID,
		&i.UserID,
		&i.ProductID,
		&i.Tier,
		&i.RedeemedAt,
	)
	return i, err
}

const insertAppleTransaction = `-- name: InsertAppleTransaction :exec
INSERT INTO apple_transactions (original_transaction_id, user_id, product_id, tier)
VALUES ($1, $2, $3, $4)
`

type InsertAppleTransactionParams struct {
	OriginalTransactionID string `json:"originalTransactionId"`
	UserID                string `json:"userId"`
	ProductID             string `json:"productId"`
	Tier                  string `json:"tier"`
}

func (q *Queries) InsertAppleTransaction(ctx context.Context, arg InsertAppleTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertAppleTransaction,
		arg.OriginalTransactionID,
		arg.UserID,
		arg.ProductID,
		arg.Tier,
	)
	return err
}

const listAppleTransactionsByUser = `-- name: ListAppleTransactionsByUser :many
SELECT original_transaction_id, user_id, product_id, tier, redeemed_at
FROM apple_transactions
WHERE user_id = $1
ORDER BY redeemed_at DESC
`

func (q *Queries) ListAppleTransactionsByUser(ctx context.Context, userID string) ([]AppleTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listAppleTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleTransaction{}
	for rows.Next() {
		var i AppleTransaction
		if err := rows.Scan(
			&i.OriginalTransactionID,
			&i.UserID,
			&i.ProductID,
			&i.Tier,
			&i.RedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
