// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deep_research.sql

package pgdb

import (
	"context"
)

const completeDeepResearchRun = `-- name: CompleteDeepResearchRun :exec
UPDATE deep_research_runs
SET status = $2,
    completed_at = NOW()
WHERE id = $1
`

type CompleteDeepResearchRunParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) CompleteDeepResearchRun(ctx context.Context, arg CompleteDeepResearchRunParams) error {
	_, err := q.db.ExecContext(ctx, completeDeepResearchRun, arg.ID, arg.Status)
	return err
}

const createDeepResearchRun = `-- name: CreateDeepResearchRun :one
INSERT INTO deep_research_runs (user_id, chat_id, run_date, status)
VALUES ($1, $2, CURRENT_DATE, 'active')
RETURNING id
`

type CreateDeepResearchRunParams struct {
	UserID string `json:"userId"`
	ChatID string `json:"chatId"`
}

func (q *Queries) CreateDeepResearchRun(ctx context.Context, arg CreateDeepResearchRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeepResearchRun, arg.UserID, arg.ChatID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveDeepResearchRun = `-- name: GetActiveDeepResearchRun :one
SELECT id, model_tokens_used
FROM deep_research_runs
WHERE user_id = $1
  AND chat_id = $2
  AND status = 'active'
ORDER BY started_at DESC
LIMIT 1
`

type GetActiveDeepResearchRunParams struct {
	UserID string `json:"userId"`
	ChatID string `json:"chatId"`
}

type GetActiveDeepResearchRunRow struct {
	ID              int64 `json:"id"`
	ModelTokensUsed int32 `json:"modelTokensUsed"`
}

func (q *Queries) GetActiveDeepResearchRun(ctx context.Context, arg GetActiveDeepResearchRunParams) (GetActiveDeepResearchRunRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveDeepResearchRun, arg.UserID, arg.ChatID)
	var i GetActiveDeepResearchRunRow
	err := row.Scan(&i.ID, &i.ModelTokensUsed)
	return i, err
}

const getDeepResearchRunCountForChat = `-- name: GetDeepResearchRunCountForChat :one
SELECT COUNT(*) as run_count
FROM deep_research_runs
WHERE user_id = $1
  AND chat_id = $2
  AND status IN ('completed', 'active')
`

type GetDeepResearchRunCountForChatParams struct {
	UserID string `json:"userId"`
	ChatID string `json:"chatId"`
}

func (q *Queries) GetDeepResearchRunCountForChat(ctx context.Context, arg GetDeepResearchRunCountForChatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeepResearchRunCountForChat, arg.UserID, arg.ChatID)
	var run_count int64
	err := row.Scan(&run_count)
	return run_count, err
}

const getUserDeepResearchRunsLifetime = `-- name: GetUserDeepResearchRunsLifetime :one
SELECT COUNT(*) as run_count
FROM deep_research_runs
WHERE user_id = $1
  AND status IN ('completed', 'active')
`

func (q *Queries) GetUserDeepResearchRunsLifetime(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserDeepResearchRunsLifetime, userID)
	var run_count int64
	err := row.Scan(&run_count)
	return run_count, err
}

const getUserDeepResearchRunsToday = `-- name: GetUserDeepResearchRunsToday :one
SELECT COUNT(*) as run_count
FROM deep_research_runs
WHERE user_id = $1
  AND run_date = CURRENT_DATE
  AND status IN ('completed', 'active')
`

func (q *Queries) GetUserDeepResearchRunsToday(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserDeepResearchRunsToday, userID)
	var run_count int64
	err := row.Scan(&run_count)
	return run_count, err
}

const hasActiveDeepResearchRun = `-- name: HasActiveDeepResearchRun :one
SELECT EXISTS(
    SELECT 1
    FROM deep_research_runs
    WHERE user_id = $1
      AND status = 'active'
) as has_active
`

func (q *Queries) HasActiveDeepResearchRun(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveDeepResearchRun, userID)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const updateDeepResearchRunTokens = `-- name: UpdateDeepResearchRunTokens :exec
UPDATE deep_research_runs
SET model_tokens_used = $2,
    plan_tokens_used = $3
WHERE id = $1
`

type UpdateDeepResearchRunTokensParams struct {
	ID              int64 `json:"id"`
	ModelTokensUsed int32 `json:"modelTokensUsed"`
	PlanTokensUsed  int32 `json:"planTokensUsed"`
}

func (q *Queries) UpdateDeepResearchRunTokens(ctx context.Context, arg UpdateDeepResearchRunTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateDeepResearchRunTokens, arg.ID, arg.ModelTokensUsed, arg.PlanTokensUsed)
	return err
}
