// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fai_payment_intents.sql

package pgdb

import (
	"context"
	"database/sql"
)

const createFaiPaymentIntent = `-- name: CreateFaiPaymentIntent :exec
INSERT INTO fai_payment_intents (
    id, user_id, payment_id, product_id, price_usd, fai_price, status
) VALUES ($1, $2, $3, $4, $5, $6, 'pending')
`

type CreateFaiPaymentIntentParams struct {
	ID        string          `json:"id"`
	UserID    string          `json:"userId"`
	PaymentID string          `json:"paymentId"`
	ProductID string          `json:"productId"`
	PriceUsd  float64         `json:"priceUsd"`
	FaiPrice  sql.NullFloat64 `json:"faiPrice"`
}

func (q *Queries) CreateFaiPaymentIntent(ctx context.Context, arg CreateFaiPaymentIntentParams) error {
	_, err := q.db.ExecContext(ctx, createFaiPaymentIntent,
		arg.ID,
		arg.UserID,
		arg.PaymentID,
		arg.ProductID,
		arg.PriceUsd,
		arg.FaiPrice,
	)
	return err
}

const getExpiredPendingFaiPaymentIntents = `-- name: GetExpiredPendingFaiPaymentIntents :many
SELECT id, user_id, payment_id, product_id, token_address, token_amount, price_usd, fai_price, status, paid_block, tx_hash, created_at, updated_at, paid_at FROM fai_payment_intents
WHERE status = 'pending'
  AND created_at < NOW() - INTERVAL '24 hours'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetExpiredPendingFaiPaymentIntents(ctx context.Context, limit int32) ([]FaiPaymentIntent, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredPendingFaiPaymentIntents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FaiPaymentIntent{}
	for rows.Next() {
		var i FaiPaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentID,
			&i.ProductID,
			&i.TokenAddress,
			&i.TokenAmount,
			&i.PriceUsd,
			&i.FaiPrice,
			&i.Status,
			&i.PaidBlock,
			&i.TxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaiPaymentIntentByPaymentID = `-- name: GetFaiPaymentIntentByPaymentID :one
SELECT id, user_id, payment_id, product_id, token_address, token_amount, price_usd, fai_price, status, paid_block, tx_hash, created_at, updated_at, paid_at FROM fai_payment_intents WHERE payment_id = $1
`

func (q *Queries) GetFaiPaymentIntentByPaymentID(ctx context.Context, paymentID string) (FaiPaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getFaiPaymentIntentByPaymentID, paymentID)
	var i FaiPaymentIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentID,
		&i.ProductID,
		&i.TokenAddress,
		&i.TokenAmount,
		&i.PriceUsd,
		&i.FaiPrice,
		&i.Status,
		&i.PaidBlock,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getFaiPaymentIntentForUser = `-- name: GetFaiPaymentIntentForUser :one
SELECT id, user_id, payment_id, product_id, token_address, token_amount, price_usd, fai_price, status, paid_block, tx_hash, created_at, updated_at, paid_at FROM fai_payment_intents WHERE payment_id = $1 AND user_id = $2
`

type GetFaiPaymentIntentForUserParams struct {
	PaymentID string `json:"paymentId"`
	UserID    string `json:"userId"`
}

func (q *Queries) GetFaiPaymentIntentForUser(ctx context.Context, arg GetFaiPaymentIntentForUserParams) (FaiPaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getFaiPaymentIntentForUser, arg.PaymentID, arg.UserID)
	var i FaiPaymentIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PaymentID,
		&i.ProductID,
		&i.TokenAddress,
		&i.TokenAmount,
		&i.PriceUsd,
		&i.FaiPrice,
		&i.Status,
		&i.PaidBlock,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const updateFaiPaymentIntentToCompleted = `-- name: UpdateFaiPaymentIntentToCompleted :exec
UPDATE fai_payment_intents
SET status = 'completed',
    token_address = $2,
    token_amount = $3,
    paid_block = $4,
    tx_hash = $5,
    paid_at = NOW(),
    updated_at = NOW()
WHERE payment_id = $1 AND status = 'pending'
`

type UpdateFaiPaymentIntentToCompletedParams struct {
	PaymentID    string          `json:"paymentId"`
	TokenAddress *string         `json:"tokenAddress"`
	TokenAmount  sql.NullFloat64 `json:"tokenAmount"`
	PaidBlock    sql.NullInt64   `json:"paidBlock"`
	TxHash       *string         `json:"txHash"`
}

func (q *Queries) UpdateFaiPaymentIntentToCompleted(ctx context.Context, arg UpdateFaiPaymentIntentToCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateFaiPaymentIntentToCompleted,
		arg.PaymentID,
		arg.TokenAddress,
		arg.TokenAmount,
		arg.PaidBlock,
		arg.TxHash,
	)
	return err
}

const updateFaiPaymentIntentToExpired = `-- name: UpdateFaiPaymentIntentToExpired :exec
UPDATE fai_payment_intents
SET status = 'expired', updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) UpdateFaiPaymentIntentToExpired(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateFaiPaymentIntentToExpired, id)
	return err
}
