// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"database/sql"
	"time"
)

type DeepResearchMessage struct {
	ID          string       `json:"id"`
	UserID      string       `json:"userId"`
	ChatID      string       `json:"chatId"`
	SessionID   string       `json:"sessionId"`
	Message     string       `json:"message"`
	MessageType string       `json:"messageType"`
	Sent        bool         `json:"sent"`
	CreatedAt   time.Time    `json:"createdAt"`
	SentAt      sql.NullTime `json:"sentAt"`
}

type DeepResearchRun struct {
	ID              int64        `json:"id"`
	UserID          string       `json:"userId"`
	ChatID          string       `json:"chatId"`
	RunDate         time.Time    `json:"runDate"`
	ModelTokensUsed int32        `json:"modelTokensUsed"`
	PlanTokensUsed  int32        `json:"planTokensUsed"`
	Status          string       `json:"status"`
	StartedAt       time.Time    `json:"startedAt"`
	CompletedAt     sql.NullTime `json:"completedAt"`
}

type Entitlement struct {
	UserID                string       `json:"userId"`
	SubscriptionExpiresAt sql.NullTime `json:"subscriptionExpiresAt"`
	UpdatedAt             time.Time    `json:"updatedAt"`
	// Subscription source: apple, stripe
	SubscriptionProvider string `json:"subscriptionProvider"`
	// Stripe Customer ID for billing portal access (cus_xxx)
	StripeCustomerID *string `json:"stripeCustomerId"`
	SubscriptionTier string  `json:"subscriptionTier"`
}

type InviteCode struct {
	ID         int64      `json:"id"`
	Code       string     `json:"code"`
	CodeHash   string     `json:"codeHash"`
	BoundEmail *string    `json:"boundEmail"`
	CreatedBy  int64      `json:"createdBy"`
	IsUsed     bool       `json:"isUsed"`
	RedeemedBy *string    `json:"redeemedBy"`
	RedeemedAt *time.Time `json:"redeemedAt"`
	ExpiresAt  *time.Time `json:"expiresAt"`
	IsActive   bool       `json:"isActive"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
}

type RequestLog struct {
	ID               int64          `json:"id"`
	UserID           string         `json:"userId"`
	Endpoint         string         `json:"endpoint"`
	Model            *string        `json:"model"`
	Provider         string         `json:"provider"`
	CreatedAt        time.Time      `json:"createdAt"`
	PromptTokens     sql.NullInt32  `json:"promptTokens"`
	CompletionTokens sql.NullInt32  `json:"completionTokens"`
	TotalTokens      sql.NullInt32  `json:"totalTokens"`
	PlanTokens       sql.NullInt32  `json:"planTokens"`
	TokenMultiplier  sql.NullString `json:"tokenMultiplier"`
}

type Task struct {
	TaskID    string    `json:"taskId"`
	UserID    string    `json:"userId"`
	ChatID    string    `json:"chatId"`
	TaskName  string    `json:"taskName"`
	TaskText  string    `json:"taskText"`
	Type      string    `json:"type"`
	Time      string    `json:"time"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type TelegramChat struct {
	ID        int64     `json:"id"`
	ChatID    int64     `json:"chatId"`
	ChatUuid  string    `json:"chatUuid"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UserRequestCountsDaily struct {
	UserID       string    `json:"userId"`
	DayBucket    time.Time `json:"dayBucket"`
	RequestCount int64     `json:"requestCount"`
}

type UserTokenUsageDaily struct {
	UserID                string    `json:"userId"`
	DayBucket             time.Time `json:"dayBucket"`
	RequestCount          int64     `json:"requestCount"`
	TotalPromptTokens     int64     `json:"totalPromptTokens"`
	TotalCompletionTokens int64     `json:"totalCompletionTokens"`
	TotalTokensUsed       int64     `json:"totalTokensUsed"`
	TotalPlanTokens       int64     `json:"totalPlanTokens"`
}
