// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem_reports.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"
)

const countProblemReportsByUserID = `-- name: CountProblemReportsByUserID :one
SELECT COUNT(*) FROM problem_reports
WHERE user_id = $1
`

func (q *Queries) CountProblemReportsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemReportsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblemReport = `-- name: CreateProblemReport :one
INSERT INTO problem_reports (
    id, user_id, problem_description,
    device_model, device_name, system_name, system_version,
    app_version, build_number, locale, timezone,
    total_capacity_bytes, available_capacity_bytes, used_capacity_bytes,
    subscription_tier, contact_email, parent_id, ticket_id, embedding,
    created_at, updated_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18, $19,
    NOW(), NOW()
)
RETURNING id, user_id, problem_description, device_model, device_name, system_name, system_version, app_version, build_number, locale, timezone, total_capacity_bytes, available_capacity_bytes, used_capacity_bytes, subscription_tier, contact_email, parent_id, ticket_id, embedding, created_at, updated_at
`

type CreateProblemReportParams struct {
	ID                     string        `json:"id"`
	UserID                 string        `json:"userId"`
	ProblemDescription     string        `json:"problemDescription"`
	DeviceModel            *string       `json:"deviceModel"`
	DeviceName             *string       `json:"deviceName"`
	SystemName             *string       `json:"systemName"`
	SystemVersion          *string       `json:"systemVersion"`
	AppVersion             *string       `json:"appVersion"`
	BuildNumber            *string       `json:"buildNumber"`
	Locale                 *string       `json:"locale"`
	Timezone               *string       `json:"timezone"`
	TotalCapacityBytes     sql.NullInt64 `json:"totalCapacityBytes"`
	AvailableCapacityBytes sql.NullInt64 `json:"availableCapacityBytes"`
	UsedCapacityBytes      sql.NullInt64 `json:"usedCapacityBytes"`
	SubscriptionTier       *string       `json:"subscriptionTier"`
	ContactEmail           *string       `json:"contactEmail"`
	ParentID               *string       `json:"parentId"`
	TicketID               *string       `json:"ticketId"`
	Embedding              interface{}   `json:"embedding"`
}

func (q *Queries) CreateProblemReport(ctx context.Context, arg CreateProblemReportParams) (ProblemReport, error) {
	row := q.db.QueryRowContext(ctx, createProblemReport,
		arg.ID,
		arg.UserID,
		arg.ProblemDescription,
		arg.DeviceModel,
		arg.DeviceName,
		arg.SystemName,
		arg.SystemVersion,
		arg.AppVersion,
		arg.BuildNumber,
		arg.Locale,
		arg.Timezone,
		arg.TotalCapacityBytes,
		arg.AvailableCapacityBytes,
		arg.UsedCapacityBytes,
		arg.SubscriptionTier,
		arg.ContactEmail,
		arg.ParentID,
		arg.TicketID,
		arg.Embedding,
	)
	var i ProblemReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemDescription,
		&i.DeviceModel,
		&i.DeviceName,
		&i.SystemName,
		&i.SystemVersion,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.Timezone,
		&i.TotalCapacityBytes,
		&i.AvailableCapacityBytes,
		&i.UsedCapacityBytes,
		&i.SubscriptionTier,
		&i.ContactEmail,
		&i.ParentID,
		&i.TicketID,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSimilarProblemReports = `-- name: FindSimilarProblemReports :many
SELECT id, user_id, problem_description, parent_id, ticket_id, created_at,
       (1 - (embedding <=> $1::vector))::float8 AS similarity
FROM problem_reports
WHERE parent_id IS NULL
  AND embedding IS NOT NULL
ORDER BY embedding <=> $1::vector
LIMIT 5
`

type FindSimilarProblemReportsRow struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"userId"`
	ProblemDescription string    `json:"problemDescription"`
	ParentID           *string   `json:"parentId"`
	TicketID           *string   `json:"ticketId"`
	CreatedAt          time.Time `json:"createdAt"`
	Similarity         float64   `json:"similarity"`
}

func (q *Queries) FindSimilarProblemReports(ctx context.Context, dollar_1 any) ([]FindSimilarProblemReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, findSimilarProblemReports, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarProblemReportsRow{}
	for rows.Next() {
		var i FindSimilarProblemReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemDescription,
			&i.ParentID,
			&i.TicketID,
			&i.CreatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentProblemReport = `-- name: GetParentProblemReport :one
SELECT id, user_id, problem_description, device_model, device_name, system_name, system_version, app_version, build_number, locale, timezone, total_capacity_bytes, available_capacity_bytes, used_capacity_bytes, subscription_tier, contact_email, parent_id, ticket_id, embedding, created_at, updated_at FROM problem_reports
WHERE id = $1 AND parent_id IS NULL
`

func (q *Queries) GetParentProblemReport(ctx context.Context, id string) (ProblemReport, error) {
	row := q.db.QueryRowContext(ctx, getParentProblemReport, id)
	var i ProblemReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemDescription,
		&i.DeviceModel,
		&i.DeviceName,
		&i.SystemName,
		&i.SystemVersion,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.Timezone,
		&i.TotalCapacityBytes,
		&i.AvailableCapacityBytes,
		&i.UsedCapacityBytes,
		&i.SubscriptionTier,
		&i.ContactEmail,
		&i.ParentID,
		&i.TicketID,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemReportByID = `-- name: GetProblemReportByID :one
SELECT id, user_id, problem_description, device_model, device_name, system_name, system_version, app_version, build_number, locale, timezone, total_capacity_bytes, available_capacity_bytes, used_capacity_bytes, subscription_tier, contact_email, parent_id, ticket_id, embedding, created_at, updated_at FROM problem_reports
WHERE id = $1
`

func (q *Queries) GetProblemReportByID(ctx context.Context, id string) (ProblemReport, error) {
	row := q.db.QueryRowContext(ctx, getProblemReportByID, id)
	var i ProblemReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemDescription,
		&i.DeviceModel,
		&i.DeviceName,
		&i.SystemName,
		&i.SystemVersion,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.Timezone,
		&i.TotalCapacityBytes,
		&i.AvailableCapacityBytes,
		&i.UsedCapacityBytes,
		&i.SubscriptionTier,
		&i.ContactEmail,
		&i.ParentID,
		&i.TicketID,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProblemReportTicketID = `-- name: UpdateProblemReportTicketID :exec
UPDATE problem_reports
SET ticket_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProblemReportTicketIDParams struct {
	ID       string  `json:"id"`
	TicketID *string `json:"ticketId"`
}

func (q *Queries) UpdateProblemReportTicketID(ctx context.Context, arg UpdateProblemReportTicketIDParams) error {
	_, err := q.db.ExecContext(ctx, updateProblemReportTicketID, arg.ID, arg.TicketID)
	return err
}
