// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem_reports.sql

package pgdb

import (
	"context"
	"database/sql"
)

const countProblemReportsByUserID = `-- name: CountProblemReportsByUserID :one
SELECT COUNT(*) FROM problem_reports
WHERE user_id = $1
`

func (q *Queries) CountProblemReportsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemReportsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblemReport = `-- name: CreateProblemReport :one
INSERT INTO problem_reports (
    id, user_id, problem_description,
    device_model, device_name, system_name, system_version,
    app_version, build_number, locale, timezone,
    total_capacity_bytes, available_capacity_bytes, used_capacity_bytes,
    subscription_tier, contact_email, ticket_id,
    created_at, updated_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    NOW(), NOW()
)
RETURNING id, user_id, problem_description, device_model, device_name, system_name, system_version, app_version, build_number, locale, timezone, total_capacity_bytes, available_capacity_bytes, used_capacity_bytes, subscription_tier, contact_email, ticket_id, created_at, updated_at
`

type CreateProblemReportParams struct {
	ID                     string        `json:"id"`
	UserID                 string        `json:"userId"`
	ProblemDescription     string        `json:"problemDescription"`
	DeviceModel            *string       `json:"deviceModel"`
	DeviceName             *string       `json:"deviceName"`
	SystemName             *string       `json:"systemName"`
	SystemVersion          *string       `json:"systemVersion"`
	AppVersion             *string       `json:"appVersion"`
	BuildNumber            *string       `json:"buildNumber"`
	Locale                 *string       `json:"locale"`
	Timezone               *string       `json:"timezone"`
	TotalCapacityBytes     sql.NullInt64 `json:"totalCapacityBytes"`
	AvailableCapacityBytes sql.NullInt64 `json:"availableCapacityBytes"`
	UsedCapacityBytes      sql.NullInt64 `json:"usedCapacityBytes"`
	SubscriptionTier       *string       `json:"subscriptionTier"`
	ContactEmail           *string       `json:"contactEmail"`
	TicketID               *string       `json:"ticketId"`
}

func (q *Queries) CreateProblemReport(ctx context.Context, arg CreateProblemReportParams) (ProblemReport, error) {
	row := q.db.QueryRowContext(ctx, createProblemReport,
		arg.ID,
		arg.UserID,
		arg.ProblemDescription,
		arg.DeviceModel,
		arg.DeviceName,
		arg.SystemName,
		arg.SystemVersion,
		arg.AppVersion,
		arg.BuildNumber,
		arg.Locale,
		arg.Timezone,
		arg.TotalCapacityBytes,
		arg.AvailableCapacityBytes,
		arg.UsedCapacityBytes,
		arg.SubscriptionTier,
		arg.ContactEmail,
		arg.TicketID,
	)
	var i ProblemReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemDescription,
		&i.DeviceModel,
		&i.DeviceName,
		&i.SystemName,
		&i.SystemVersion,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.Timezone,
		&i.TotalCapacityBytes,
		&i.AvailableCapacityBytes,
		&i.UsedCapacityBytes,
		&i.SubscriptionTier,
		&i.ContactEmail,
		&i.TicketID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemReportByID = `-- name: GetProblemReportByID :one
SELECT id, user_id, problem_description, device_model, device_name, system_name, system_version, app_version, build_number, locale, timezone, total_capacity_bytes, available_capacity_bytes, used_capacity_bytes, subscription_tier, contact_email, ticket_id, created_at, updated_at FROM problem_reports
WHERE id = $1
`

func (q *Queries) GetProblemReportByID(ctx context.Context, id string) (ProblemReport, error) {
	row := q.db.QueryRowContext(ctx, getProblemReportByID, id)
	var i ProblemReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemDescription,
		&i.DeviceModel,
		&i.DeviceName,
		&i.SystemName,
		&i.SystemVersion,
		&i.AppVersion,
		&i.BuildNumber,
		&i.Locale,
		&i.Timezone,
		&i.TotalCapacityBytes,
		&i.AvailableCapacityBytes,
		&i.UsedCapacityBytes,
		&i.SubscriptionTier,
		&i.ContactEmail,
		&i.TicketID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
