// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_facts.sql

package pgdb

import (
	"context"
)

const createUserFact = `-- name: CreateUserFact :one
INSERT INTO users_facts (id, user_id, fact_body, fact_type, created_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, user_id, fact_body, fact_type, created_at
`

type CreateUserFactParams struct {
	ID       string `json:"id"`
	UserID   string `json:"userId"`
	FactBody string `json:"factBody"`
	FactType string `json:"factType"`
}

func (q *Queries) CreateUserFact(ctx context.Context, arg CreateUserFactParams) (UsersFact, error) {
	row := q.db.QueryRowContext(ctx, createUserFact,
		arg.ID,
		arg.UserID,
		arg.FactBody,
		arg.FactType,
	)
	var i UsersFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactBody,
		&i.FactType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserFact = `-- name: DeleteUserFact :exec
DELETE FROM users_facts
WHERE id = $1 AND user_id = $2
`

type DeleteUserFactParams struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
}

func (q *Queries) DeleteUserFact(ctx context.Context, arg DeleteUserFactParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserFact, arg.ID, arg.UserID)
	return err
}

const deleteUserFactsByUserID = `-- name: DeleteUserFactsByUserID :exec
DELETE FROM users_facts
WHERE user_id = $1
`

func (q *Queries) DeleteUserFactsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserFactsByUserID, userID)
	return err
}

const getUserFactByID = `-- name: GetUserFactByID :one
SELECT id, user_id, fact_body, fact_type, created_at FROM users_facts
WHERE id = $1
`

func (q *Queries) GetUserFactByID(ctx context.Context, id string) (UsersFact, error) {
	row := q.db.QueryRowContext(ctx, getUserFactByID, id)
	var i UsersFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FactBody,
		&i.FactType,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFactsByUserID = `-- name: GetUserFactsByUserID :many
SELECT id, user_id, fact_body, fact_type, created_at FROM users_facts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserFactsByUserID(ctx context.Context, userID string) ([]UsersFact, error) {
	rows, err := q.db.QueryContext(ctx, getUserFactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersFact{}
	for rows.Next() {
		var i UsersFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FactBody,
			&i.FactType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFactsByUserIDAndType = `-- name: GetUserFactsByUserIDAndType :many
SELECT id, user_id, fact_body, fact_type, created_at FROM users_facts
WHERE user_id = $1 AND fact_type = $2
ORDER BY created_at DESC
`

type GetUserFactsByUserIDAndTypeParams struct {
	UserID   string `json:"userId"`
	FactType string `json:"factType"`
}

func (q *Queries) GetUserFactsByUserIDAndType(ctx context.Context, arg GetUserFactsByUserIDAndTypeParams) ([]UsersFact, error) {
	rows, err := q.db.QueryContext(ctx, getUserFactsByUserIDAndType, arg.UserID, arg.FactType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersFact{}
	for rows.Next() {
		var i UsersFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FactBody,
			&i.FactType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
