// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zcash_payments.sql

package pgdb

import (
	"context"
)

const getZcashPayment = `-- name: GetZcashPayment :one
SELECT invoice_id, user_id, product_id, amount_zat, redeemed_at
FROM zcash_payments
WHERE invoice_id = $1
`

func (q *Queries) GetZcashPayment(ctx context.Context, invoiceID string) (ZcashPayment, error) {
	row := q.db.QueryRowContext(ctx, getZcashPayment, invoiceID)
	var i ZcashPayment
	err := row.Scan(
		&i.InvoiceID,
		&i.UserID,
		&i.ProductID,
		&i.AmountZat,
		&i.RedeemedAt,
	)
	return i, err
}

const insertZcashPayment = `-- name: InsertZcashPayment :exec
INSERT INTO zcash_payments (invoice_id, user_id, product_id, amount_zat)
VALUES ($1, $2, $3, $4)
`

type InsertZcashPaymentParams struct {
	InvoiceID string `json:"invoiceId"`
	UserID    string `json:"userId"`
	ProductID string `json:"productId"`
	AmountZat int64  `json:"amountZat"`
}

func (q *Queries) InsertZcashPayment(ctx context.Context, arg InsertZcashPaymentParams) error {
	_, err := q.db.ExecContext(ctx, insertZcashPayment,
		arg.InvoiceID,
		arg.UserID,
		arg.ProductID,
		arg.AmountZat,
	)
	return err
}

const listZcashPaymentsByUser = `-- name: ListZcashPaymentsByUser :many
SELECT invoice_id, user_id, product_id, amount_zat, redeemed_at
FROM zcash_payments
WHERE user_id = $1
ORDER BY redeemed_at DESC
`

func (q *Queries) ListZcashPaymentsByUser(ctx context.Context, userID string) ([]ZcashPayment, error) {
	rows, err := q.db.QueryContext(ctx, listZcashPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZcashPayment{}
	for rows.Next() {
		var i ZcashPayment
		if err := rows.Scan(
			&i.InvoiceID,
			&i.UserID,
			&i.ProductID,
			&i.AmountZat,
			&i.RedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
