// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zcash_invoices.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createZcashInvoice = `-- name: CreateZcashInvoice :exec
INSERT INTO zcash_invoices (
    id, user_id, product_id, amount_zatoshis, zec_amount,
    price_usd, receiving_address, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
`

type CreateZcashInvoiceParams struct {
	ID               uuid.UUID `json:"id"`
	UserID           string    `json:"userId"`
	ProductID        string    `json:"productId"`
	AmountZatoshis   int64     `json:"amountZatoshis"`
	ZecAmount        float64   `json:"zecAmount"`
	PriceUsd         float64   `json:"priceUsd"`
	ReceivingAddress string    `json:"receivingAddress"`
}

func (q *Queries) CreateZcashInvoice(ctx context.Context, arg CreateZcashInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, createZcashInvoice,
		arg.ID,
		arg.UserID,
		arg.ProductID,
		arg.AmountZatoshis,
		arg.ZecAmount,
		arg.PriceUsd,
		arg.ReceivingAddress,
	)
	return err
}

const getExpiredPendingInvoices = `-- name: GetExpiredPendingInvoices :many
SELECT id, user_id, product_id, amount_zatoshis, zec_amount, price_usd, receiving_address, status, created_at, updated_at, paid_at FROM zcash_invoices
WHERE status = 'pending'
  AND created_at < NOW() - INTERVAL '24 hours'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetExpiredPendingInvoices(ctx context.Context, limit int32) ([]ZcashInvoice, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredPendingInvoices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZcashInvoice{}
	for rows.Next() {
		var i ZcashInvoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.AmountZatoshis,
			&i.ZecAmount,
			&i.PriceUsd,
			&i.ReceivingAddress,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getZcashInvoice = `-- name: GetZcashInvoice :one
SELECT id, user_id, product_id, amount_zatoshis, zec_amount, price_usd, receiving_address, status, created_at, updated_at, paid_at FROM zcash_invoices WHERE id = $1
`

func (q *Queries) GetZcashInvoice(ctx context.Context, id uuid.UUID) (ZcashInvoice, error) {
	row := q.db.QueryRowContext(ctx, getZcashInvoice, id)
	var i ZcashInvoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AmountZatoshis,
		&i.ZecAmount,
		&i.PriceUsd,
		&i.ReceivingAddress,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getZcashInvoiceForUser = `-- name: GetZcashInvoiceForUser :one
SELECT id, user_id, product_id, amount_zatoshis, zec_amount, price_usd, receiving_address, status, created_at, updated_at, paid_at FROM zcash_invoices WHERE id = $1 AND user_id = $2
`

type GetZcashInvoiceForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"userId"`
}

func (q *Queries) GetZcashInvoiceForUser(ctx context.Context, arg GetZcashInvoiceForUserParams) (ZcashInvoice, error) {
	row := q.db.QueryRowContext(ctx, getZcashInvoiceForUser, arg.ID, arg.UserID)
	var i ZcashInvoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AmountZatoshis,
		&i.ZecAmount,
		&i.PriceUsd,
		&i.ReceivingAddress,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getZcashInvoicesByUserAndStatus = `-- name: GetZcashInvoicesByUserAndStatus :many
SELECT id, user_id, product_id, amount_zatoshis, zec_amount, price_usd, receiving_address, status, created_at, updated_at, paid_at FROM zcash_invoices
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
`

type GetZcashInvoicesByUserAndStatusParams struct {
	UserID string `json:"userId"`
	Status string `json:"status"`
}

func (q *Queries) GetZcashInvoicesByUserAndStatus(ctx context.Context, arg GetZcashInvoicesByUserAndStatusParams) ([]ZcashInvoice, error) {
	rows, err := q.db.QueryContext(ctx, getZcashInvoicesByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZcashInvoice{}
	for rows.Next() {
		var i ZcashInvoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.AmountZatoshis,
			&i.ZecAmount,
			&i.PriceUsd,
			&i.ReceivingAddress,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZcashInvoiceStatus = `-- name: UpdateZcashInvoiceStatus :exec
UPDATE zcash_invoices
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateZcashInvoiceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateZcashInvoiceStatus(ctx context.Context, arg UpdateZcashInvoiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateZcashInvoiceStatus, arg.ID, arg.Status)
	return err
}

const updateZcashInvoiceToExpired = `-- name: UpdateZcashInvoiceToExpired :exec
UPDATE zcash_invoices
SET status = 'expired', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateZcashInvoiceToExpired(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateZcashInvoiceToExpired, id)
	return err
}

const updateZcashInvoiceToPaid = `-- name: UpdateZcashInvoiceToPaid :exec
UPDATE zcash_invoices
SET status = 'paid', paid_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateZcashInvoiceToPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateZcashInvoiceToPaid, id)
	return err
}

const updateZcashInvoiceToProcessing = `-- name: UpdateZcashInvoiceToProcessing :exec
UPDATE zcash_invoices
SET status = 'processing', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateZcashInvoiceToProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateZcashInvoiceToProcessing, id)
	return err
}
