// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tasks

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id string) error
	DeleteTaskByIDAndChatID(ctx context.Context, arg DeleteTaskByIDAndChatIDParams) error
	DeleteTaskByIDAndUserID(ctx context.Context, arg DeleteTaskByIDAndUserIDParams) error
	GetTaskByID(ctx context.Context, id string) (Task, error)
	GetTasksByChatID(ctx context.Context, chatID string) ([]Task, error)
	GetTasksByUserID(ctx context.Context, userID string) ([]Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
